"""Tests for the documentation-facts generator (`tools/doc_facts.py`).

Documentation drift is a shipped defect in this repository's history ("14 vs 19
strategies", "49/54 vs actual test count", "24 strategies" next to a 27-row
registry). These tests pin the gate that stops it: every marked block in the
committed docs must equal what the registry and the suite say now, and a change
to either must be detected.
"""
from __future__ import annotations

import importlib.util
import os
import shutil
import sys

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from nbacomp import strategies as S  # noqa: E402


def _load_tool():
    path = os.path.join(REPO, "tools", "doc_facts.py")
    spec = importlib.util.spec_from_file_location("doc_facts", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


doc_facts = _load_tool()


def test_committed_docs_match_the_repository():
    """The CI gate itself: `python tools/doc_facts.py --check` must pass."""
    assert doc_facts.main(["--check"]) == 0


def test_every_declared_block_is_present_in_its_file():
    for path, blocks in doc_facts.BLOCKS.items():
        with open(os.path.join(REPO, path)) as f:
            text = f.read()
        for name in blocks:
            begin, end = doc_facts._markers(name)
            assert begin in text, f"{path} is missing {begin}"
            assert end in text, f"{path} is missing {end}"
            assert text.index(begin) < text.index(end), f"{path}: {name} not closed"


def test_strategy_block_lists_every_registered_strategy():
    rendered = doc_facts.render("README.md", "")
    for sid in S.STRATEGIES:
        assert f"| {sid} | {S.STRATEGIES[sid]['username']} |" in rendered, sid


def test_suite_counts_are_pytest_items_not_just_functions():
    """The number quoted must be the one pytest reports, not a smaller proxy.

    An earlier draft of the generator published the AST count of `def test_*`
    (231) as "pytest collects 231 tests" while pytest collected 236 — a false
    claim generated by the tool that exists to stop false claims.
    """
    items = doc_facts.test_items()
    funcs = doc_facts.test_functions()
    assert items, "pytest is installed in CI; the real count must be used"
    assert sum(items.values()) >= sum(funcs.values())
    block = doc_facts.block_suite("")
    assert f"**{sum(items.values())} tests**" in block
    head = doc_facts.block_headline("")
    assert f"**{sum(items.values())} tests**" in head
    assert f"{sum(funcs.values())} test functions" in head


def test_drift_is_detected(tmp_path):
    """Change a figure in a copy of the README and the gate must fail."""
    for name in doc_facts.BLOCKS:
        shutil.copy(os.path.join(REPO, name), tmp_path / name)
    readme = tmp_path / "README.md"
    text = readme.read_text()
    # corrupt the generated strategy count claim inside the marked block
    old = f"strategies registered: **{len(S.STRATEGIES)}**"
    assert old in text
    readme.write_text(text.replace(old, "strategies registered: **24**"))
    original_root = doc_facts.ROOT
    doc_facts.ROOT = str(tmp_path)
    try:
        assert doc_facts.check("") == 1
    finally:
        doc_facts.ROOT = original_root


def test_volatile_row_counts_are_not_quoted_in_prose():
    """Row counts move every collection run, so prose must point at the artifact.

    The generated headline says so explicitly; the README's own 'Current state'
    section must not reintroduce a hand-copied count table.
    """
    with open(os.path.join(REPO, "README.md")) as f:
        text = f.read()
    assert "data/db_report.txt" in text
    assert "| table | rows | note |" not in text
