"""Source registry — every data source with access terms and verification state.

Verification dates are real: '2026-09-20' entries were checked during the
initial build (sandbox GitHub-token environment); entries whose reachability
could not be confirmed from this environment say so explicitly and are
re-checked automatically by the nightly GitHub Actions collector, which
updates source_status in the database (surfaced on the site's Sources page).
"""
from __future__ import annotations

VERIFIED = "2026-09-20"

REGISTRY: list[dict] = [
    {
        "id": "espn:scoreboard",
        "name": "ESPN site API — NBA scoreboard (site.web host)",
        "url": "https://site.web.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard",
        "data_type": "schedule, tipoff times, live/final scores, current odds (spread/total/ML, provider-attributed)",
        "nba_relevance": "primary schedule + results + current-price feed",
        "historical_depth": "full history by date (verified: 2025-06-05 and 2026-01-15 both 200); odds only persist for near-term games",
        "update_frequency": "near-real-time",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; we self-limit to ~1 request/second",
        "terms": "public site API; research display with source attribution",
        "reliability": "DEGRADED 2026-09-20: 629 consecutive collection failures; BOTH ESPN hosts now Akamai-403 plain-HTTP fingerprints from runner IPs. Collector falls back to Node-fetch transport automatically (runner-verified 200 for the same URLs); Basketball-Reference is the schedule/results backstop.",
        "last_verified": VERIFIED,
        "verification_note": "RUNNER-VERIFIED 2026-09-20: site.api.espn.com returns Akamai 403 to runner TLS fingerprints (python AND curl); the earlier site.web-200 result no longer reproduces (full collection_log in DB shows the failure run). Collector tries site.web then site.api via urllib, then Node fetch against both hosts; the winning transport is recorded per fetch in source_status.detail. The block pattern was also documented by sibling project NBAInjuryReport.",
        "backup_source": "basketball-reference (scores), kalshi (settlements)",
    },
    {
        "id": "espn:injuries",
        "name": "ESPN site API — NBA injuries (site.web host)",
        "url": "https://site.web.api.espn.com/apis/site/v2/sports/basketball/nba/injuries",
        "data_type": "player injury status, dates, notes by team (~860KB full-league board)",
        "nba_relevance": "injury-strategy signal source",
        "historical_depth": "current snapshot only (no free archive) — forward collection builds history going forward",
        "update_frequency": "near-real-time",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; self-limited",
        "terms": "public site API; research use with attribution",
        "reliability": "medium-high; ESPN is NOT official league confirmation (marked on every use). Shares the scoreboard transport path (urllib -> Node-fetch fallback).",
        "last_verified": VERIFIED,
        "verification_note": "RUNNER-VERIFIED 2026-09-20: HTTP 200, 859,816-byte payload. (Sibling project audit observed 75 rows / 27 team blocks on 2026-09-19.) Later the same day both ESPN hosts began 403ing runner fingerprints; Node-fetch fallback added.",
        "backup_source": "nba.com official injury report page (PDF; discovery attempted each run)",
    },
    {
        "id": "espn:summary",
        "name": "ESPN site API — game summary / box scores",
        "url": "https://site.web.api.espn.com/apis/site/v2/sports/basketball/nba/summary?event=ID",
        "data_type": "full box scores (player MIN/PTS/REB/AST/STL/BLK/TO/FG/3PT/FT/+/-, starters, DNP reasons), team box lines (FGA/OREB/TOV/FTA), game injuries",
        "nba_relevance": "player game logs + possession-based pace/efficiency features (replaces blocked stats.nba.com)",
        "historical_depth": "by game id (historical finals verified)",
        "update_frequency": "post-game",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; self-limited ~1.2 rps",
        "terms": "public site API; research use",
        "reliability": "high when reachable; shares the scoreboard transport path (urllib -> Node-fetch fallback)",
        "last_verified": VERIFIED,
        "verification_note": "RUNNER-VERIFIED 2026-09-20: HTTP 200 with boxscore=True athletes=True injuries=True for a historical game; parser pinned to the verified payload shape by unit test.",
        "backup_source": "basketball-reference box scores",
    },
    {
        "id": "bref:monthly-games",
        "name": "Basketball-Reference — monthly results pages",
        "url": "https://www.basketball-reference.com/leagues/NBA_2026_games-january.html",
        "data_type": "every game's date, matchup, tipoff time and final score per month (independent of ESPN and Kalshi); scheduled (unplayed) rows included",
        "nba_relevance": "schedule/results backfill source (finals AND upcoming games with ET->UTC tipoffs) plus the independent score verification layer (ESPN ↔ BBR cross-check)",
        "historical_depth": "decades",
        "update_frequency": "post-game",
        "access_method": "public HTML, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "site asks ~1 request/second compliance; we respect it",
        "terms": "public site; research use with attribution",
        "reliability": "high",
        "last_verified": VERIFIED,
        "verification_note": "RUNNER-VERIFIED 2026-09-20: HTTP 200 (268KB page). Reachability re-checked every collection run.",
        "backup_source": "kalshi settled results (exchange settlement truth)",
    },
    {
        "id": "nba:stats",
        "name": "stats.nba.com — BLOCKED from CI runners (documented, replaced)",
        "url": "https://stats.nba.com/stats/",
        "data_type": "(would be) official game logs and advanced stats",
        "nba_relevance": "intended official-statistics backbone",
        "historical_depth": "n/a for this deployment",
        "update_frequency": "n/a",
        "access_method": "public JSON, keyless, browser-like headers",
        "cost": "free (where reachable)", "registration_required": False,
        "paid_plan_required": False, "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "public league data",
        "reliability": "UNUSABLE HERE: runner probes 2026-09-20 show read-timeouts (urllib, curl AND Node fetch) — connection tarpitted from GitHub-hosted runner IPs; data.nba.net also dead; cdn.nba.com liveData 403 (Akamai).",
        "last_verified": VERIFIED,
        "verification_note": "Documented honestly and engineered around: ESPN summary box scores provide the same fields we actually modeled on (team possessions inputs, player logs); Basketball-Reference + Kalshi settlements provide independent verification. If a future environment can reach stats.nba.com, the collectors in nbacomp/sources/nba.py are ready.",
        "backup_source": "espn:summary, bref:monthly-games",
    },
    {
        "id": "kalshi:api",
        "name": "Kalshi public market-data API (trade-api/v2)",
        "url": "https://api.elections.kalshi.com/trade-api/v2",
        "data_type": "NBA contract markets: series/events/markets, quotes (bid/ask/last), volume, open interest, orderbooks, candlesticks, trades, official settlement results",
        "nba_relevance": "execution venue + price history for backtests + settlement ground truth",
        "historical_depth": "FORWARD-ONLY: settled events are enumerable (1448+ KXNBAGAME over 8 pages) but their MARKETS are not retrievable by any public endpoint (verified 2026-09-21) — no settled prices or results exist via API. Price history is built by forward candle accumulation on open markets (which carry candles from listing, e.g. 2026-10-20 openers since 2026-08-20).",
        "update_frequency": "live",
        "access_method": "public GET endpoints, keyless (market data); trading would require an account (not used)",
        "cost": "free (market data)", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "basic tier ~10 rps documented; we self-limit to ~3 rps",
        "terms": "Kalshi API terms; public market data. Fee model (0.07·C·P·(1−P)) per Kalshi docs",
        "reliability": "high",
        "last_verified": VERIFIED,
        "verification_note": "RUNNER-VERIFIED 2026-09-20: keyless 200s; series confirmed to exist: KXNBAGAME, KXNBASPREAD, KXNBATOTAL, KXNBA1H, KXNBAPTS, KXNBAREB, KXNBAAST, KXNBAPRA, KXNBASTL, KXNBABLK, KXNBAMVP (KXNBAPOINT/KXNBATHREES/KXNBATO/KXNBADD do not exist). Opening-night 2026-10-20 game-winner markets already listed. Verified payload shapes (live, pinned by unit test): KXNBAGAME lists ONE market per team (ticker ...{EVENT}-{TEAM}, title '{Team} wins', yes_sub_title='{Team}'); all quotes are DOLLAR STRINGS (yes_bid_dollars '0.5400' etc, volume_fp/open_interest_fp in contracts); orderbooks nest under orderbook_fp.yes_dollars/no_dollars as ASCENDING [price,size] dollar-string pairs; candlesticks require market_tickers+period_interval (seconds, NOT ms) and return {markets:[{market_ticker, candlesticks:[{end_period_ts, price:{open/high/low/close/mean/previous_dollars}, volume_fp, yes_bid/yes_ask OHLC}]}]}. Caveats: /markets?series+status=settled returns 0 rows; settled history is walked via /events?series_ticker=S&status=settled cursor pagination. Settled event rows expose title ('Game 5: New York at San Antonio') and sub_title ('NYK at SAS (Jun 13)') but NOT ticker/close_time keys — event identity is the event_ticker field whose encoding carries the ET game date and team abbrevs.",
        "backup_source": "espn:scoreboard odds (price cross-check)",
    },
    {
        "id": "balldontlie:api",
        "name": "BallDon'tLie API v1 — free, keyless bulk season data",
        "url": "https://www.balldontlie.io/api/v1/",
        "data_type": "season game lists (dates, matchups, final scores), per-game box scores (per-player MIN/PTS/REB/AST/STL/BLK/TO/FG/3PT/FT/+/-), per-team and per-player per-season aggregates",
        "nba_relevance": "deep-history box scores (seasons older than the per-game ESPN walk has reached), team/player season aggregates, and an independent final-score cross-check",
        "historical_depth": "multi-season (requested seasons 2020-2024 at launch; the seasons[] parameter's year semantics are verified from the returned data itself and any mismatch is flagged, not silently corrected)",
        "update_frequency": "post-game (aggregates)",
        "access_method": "public JSON, keyless (no account, no trial)",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; self-limited to ~2 rps with a per-run request budget and resumable cursors",
        "terms": "public service; research use with attribution",
        "reliability": "medium-high: aggregates public league data via a separate pipeline — SEMI-independent for cross-checking (a genuine score conflict between it and ESPN/BRef is recorded as a critical anomaly, never resolved silently). Reachability from CI runners is verified at runtime and recorded in source_status; if unreachable the collectors log failures and the ESPN walk remains the primary channel.",
        "last_verified": "2026-09-21",
        "verification_note": "Added 2026-09-21 after the ESPN box-score walk was measured at ~2 weeks to reach 2023-24. Collector stores team rows with OREB=NULL (the source does not split rebounds) and the model treats such rows as pace-unavailable (never 0) so no possession feature is silently biased. Verification role: every balldontlie final is cross-checked against the existing games row — matches set the verified flag, conflicts are recorded with both values.",
        "backup_source": "espn:summary (primary box scores), bref:monthly-games (score verification)",
    },
    {
        "id": "kalshi:docs",
        "name": "Kalshi documentation (fee schedule, settlement rules)",
        "url": "https://docs.kalshi.com/",
        "data_type": "fee formula, contract rules",
        "nba_relevance": "execution-cost modeling",
        "historical_depth": "n/a",
        "update_frequency": "as published",
        "access_method": "public web",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "public docs",
        "reliability": "high",
        "last_verified": VERIFIED,
        "verification_note": "Fee formula 0.07·C·P·(1−P) implemented in nbacomp/util.py with unit test.",
        "backup_source": None,
    },
    {
        "id": "sibling:nba-injury-report",
        "name": "MasterSite sibling: NBAInjuryReport",
        "url": "https://buffedlizard55-lab.github.io/NBAInjuryReport/",
        "data_type": "running injury-monitoring methodology, ESPN injury endpoint audits, official NBA injury-report PDF discovery attempts",
        "nba_relevance": "source-verification intelligence reused in our registry and collectors",
        "historical_depth": "their audit history (published)",
        "update_frequency": "every 10 minutes (their CI)",
        "access_method": "public site + public GitHub repo",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a (their data, not piped)",
        "terms": "public",
        "reliability": "high as a meta-audit; their findings (ESPN 403 episodes, official-report 404) are incorporated as documented facts",
        "last_verified": VERIFIED,
        "verification_note": "README + AUDIT.md read 2026-09-20 via GitHub API during build.",
        "backup_source": None,
    },
    {
        "id": "rejected:paid-odds-archives",
        "name": "Paid historical odds archives (Scottfree etc.) — NOT USED",
        "url": "https://shop.scottfreellc.com/shop/p/nba-historical-odds-data",
        "data_type": "historical closing lines (paid)",
        "nba_relevance": "would enable deep historical totals/spread backtests",
        "historical_depth": "multi-season",
        "update_frequency": "n/a",
        "access_method": "purchase required",
        "cost": "paid — EXCLUDED from core pipeline by policy",
        "registration_required": True, "paid_plan_required": True,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "commercial license",
        "reliability": "not evaluated (not purchased)",
        "last_verified": VERIFIED,
        "verification_note": "Documented as the known limitation it is: without paid archives, historical sportsbook totals/spread prices are unavailable free; Kalshi candlesticks + forward collection are our honest substitutes.",
        "backup_source": "kalshi:candles",
    },
    {
        "id": "master-site",
        "name": "MasterSite (sibling project directory)",
        "url": "https://buffedlizard55-lab.github.io/MasterSite/",
        "data_type": "verified directory of sibling sites with audit ledger",
        "nba_relevance": "reused: NBAInjuryReport injury methodology, PriceKalshiHistorical Kalshi collector patterns, KalshiPaperSim paper-trading patterns, Commodities Actions-collector pattern",
        "historical_depth": "n/a",
        "update_frequency": "hourly audits",
        "access_method": "public",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "public",
        "reliability": "high (API-verified directory)",
        "last_verified": VERIFIED,
        "verification_note": "Reviewed 2026-09-20 (live site + repo APIs). Findings recorded in the research log (R-001).",
        "backup_source": None,
    },
]
