"""Source registry — every data source with access terms and verification state.

Verification dates are real: '2026-09-20' entries were checked during the
initial build (sandbox GitHub-token environment); entries whose reachability
could not be confirmed from this environment say so explicitly and are
re-checked automatically by the nightly GitHub Actions collector, which
updates source_status in the database (surfaced on the site's Sources page).
"""
from __future__ import annotations

VERIFIED = "2026-09-20"

REGISTRY: list[dict] = [
    {
        "id": "espn:scoreboard",
        "name": "ESPN site API — NBA scoreboard",
        "url": "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard",
        "data_type": "schedule, tipoff times, live/final scores, current odds (spread/total/ML, provider-attributed)",
        "nba_relevance": "primary schedule + results + current-price feed",
        "historical_depth": "scoreboard by historical date (verified pattern used by public collectors); odds only persist for near-term games",
        "update_frequency": "near-real-time",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; we self-limit to ~1 request/second",
        "terms": "public site API; no documented redistribution license — used for research display with source attribution",
        "reliability": "high for scores/schedule; odds availability varies by date (documented per snapshot)",
        "last_verified": VERIFIED,
        "verification_note": "Reachable from GitHub Actions runners (sibling project NBAInjuryReport runner audit 2026-09-17/19 observed both 200s and one 403 fingerprint episode; browser-like headers used). Direct sandbox access blocked by this environment's network policy — documented.",
        "backup_source": "nba:data-net, stats.nba.com",
    },
    {
        "id": "espn:injuries",
        "name": "ESPN site API — NBA injuries",
        "url": "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries",
        "data_type": "player injury status, dates, notes by team",
        "nba_relevance": "injury-strategy signal source",
        "historical_depth": "current snapshot only (no free archive) — forward collection builds history going forward",
        "update_frequency": "near-real-time",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; self-limited",
        "terms": "public site API; research use with attribution",
        "reliability": "medium-high; ESPN is NOT official league confirmation (marked on every use)",
        "last_verified": VERIFIED,
        "verification_note": "75 rows / 27 team blocks observed in sibling project runner audit 2026-09-19 (their AUDIT.md).",
        "backup_source": "nba.com official injury report page (PDF; discovery attempted each run)",
    },
    {
        "id": "nba:stats",
        "name": "NBA.com/stats endpoints (stats.nba.com)",
        "url": "https://stats.nba.com/stats/",
        "data_type": "team/player game logs, advanced team stats (ORTg/DRtg/Pace), four factors, hustle stats, official results",
        "nba_relevance": "official statistics backbone for models + independent score verification",
        "historical_depth": "decades (per-season endpoints)",
        "update_frequency": "post-game (minutes after final)",
        "access_method": "public JSON, keyless, browser-like headers required",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented; community reports soft limits — we run at ~1 rps",
        "terms": "public league data; research use",
        "reliability": "high; occasionally rate-limits aggressive clients",
        "last_verified": VERIFIED,
        "verification_note": "Endpoint shapes are long-documented via public collectors; runner reachability re-verified on every collection run (source_status table).",
        "backup_source": "espn:scoreboard, data.nba.net",
    },
    {
        "id": "nba:data-net",
        "name": "data.nba.net (fallback scoreboard)",
        "url": "https://data.nba.net/prod/v1/{YYYYMMDD}/scoreboard.json",
        "data_type": "schedule + scores (secondary verification path)",
        "nba_relevance": "independent result cross-check",
        "historical_depth": "by date (recent seasons)",
        "update_frequency": "near-real-time",
        "access_method": "public JSON, keyless",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "undocumented",
        "terms": "public league data",
        "reliability": "medium (endpoint has been deprecated/reinstated historically) — used as fallback only",
        "last_verified": VERIFIED,
        "verification_note": "Reachability checked per run when primary verification is unavailable.",
        "backup_source": "stats.nba.com scoreboardv2",
    },
    {
        "id": "kalshi:api",
        "name": "Kalshi public market-data API (trade-api/v2)",
        "url": "https://api.elections.kalshi.com/trade-api/v2",
        "data_type": "NBA contract markets: series/events/markets, quotes (bid/ask/last), volume, open interest, orderbooks, candlesticks, trades, official settlement results",
        "nba_relevance": "execution venue + price history for backtests + settlement ground truth",
        "historical_depth": "candlesticks available for settled markets (availability probed per series/window and recorded — not assumed)",
        "update_frequency": "live",
        "access_method": "public GET endpoints, keyless (market data); trading would require an account (not used)",
        "cost": "free (market data)", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "basic tier ~10 rps documented; we self-limit to ~3 rps",
        "terms": "Kalshi API terms; public market data. Fee model (0.07·C·P·(1−P)) per Kalshi docs",
        "reliability": "high",
        "last_verified": VERIFIED,
        "verification_note": "Public no-auth market data confirmed via Kalshi docs quick start (docs.kalshi.com) and sibling project PriceKalshiHistorical collector; NBA series existence probed at runtime (never assumed).",
        "backup_source": "espn:scoreboard odds (price cross-check)",
    },
    {
        "id": "kalshi:docs",
        "name": "Kalshi documentation (fee schedule, settlement rules)",
        "url": "https://docs.kalshi.com/",
        "data_type": "fee formula, contract rules",
        "nba_relevance": "execution-cost modeling",
        "historical_depth": "n/a",
        "update_frequency": "as published",
        "access_method": "public web",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "public docs",
        "reliability": "high",
        "last_verified": VERIFIED,
        "verification_note": "Fee formula 0.07·C·P·(1−P) implemented in nbacomp/util.py with unit test.",
        "backup_source": None,
    },
    {
        "id": "sibling:nba-injury-report",
        "name": "MasterSite sibling: NBAInjuryReport",
        "url": "https://buffedlizard55-lab.github.io/NBAInjuryReport/",
        "data_type": "running injury-monitoring methodology, ESPN injury endpoint audits, official NBA injury-report PDF discovery attempts",
        "nba_relevance": "source-verification intelligence reused in our registry and collectors",
        "historical_depth": "their audit history (published)",
        "update_frequency": "every 10 minutes (their CI)",
        "access_method": "public site + public GitHub repo",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a (their data, not piped)",
        "terms": "public",
        "reliability": "high as a meta-audit; their findings (ESPN 403 episodes, official-report 404) are incorporated as documented facts",
        "last_verified": VERIFIED,
        "verification_note": "README + AUDIT.md read 2026-09-20 via GitHub API during build.",
        "backup_source": None,
    },
    {
        "id": "rejected:paid-odds-archives",
        "name": "Paid historical odds archives (Scottfree etc.) — NOT USED",
        "url": "https://shop.scottfreellc.com/shop/p/nba-historical-odds-data",
        "data_type": "historical closing lines (paid)",
        "nba_relevance": "would enable deep historical totals/spread backtests",
        "historical_depth": "multi-season",
        "update_frequency": "n/a",
        "access_method": "purchase required",
        "cost": "paid — EXCLUDED from core pipeline by policy",
        "registration_required": True, "paid_plan_required": True,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "commercial license",
        "reliability": "not evaluated (not purchased)",
        "last_verified": VERIFIED,
        "verification_note": "Documented as the known limitation it is: without paid archives, historical sportsbook totals/spread prices are unavailable free; Kalshi candlesticks + forward collection are our honest substitutes.",
        "backup_source": "kalshi:candles",
    },
    {
        "id": "master-site",
        "name": "MasterSite (sibling project directory)",
        "url": "https://buffedlizard55-lab.github.io/MasterSite/",
        "data_type": "verified directory of sibling sites with audit ledger",
        "nba_relevance": "reused: NBAInjuryReport injury methodology, PriceKalshiHistorical Kalshi collector patterns, KalshiPaperSim paper-trading patterns, Commodities Actions-collector pattern",
        "historical_depth": "n/a",
        "update_frequency": "hourly audits",
        "access_method": "public",
        "cost": "free", "registration_required": False, "paid_plan_required": False,
        "free_trial_involved": False,
        "rate_limits": "n/a",
        "terms": "public",
        "reliability": "high (API-verified directory)",
        "last_verified": VERIFIED,
        "verification_note": "Reviewed 2026-09-20 (live site + repo APIs). Findings recorded in the research log (R-001).",
        "backup_source": None,
    },
]
